{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from commons import *"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Read the Data Source Files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "dfDatasets = pd.read_csv(FILE_DATASETS)\n",
    "dfMetafeatures = pd.read_csv(FILE_METAFEATURES, delimiter=\";\")\n",
    "datasets = list(dfDatasets[\"openmlid\"].values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  interactivity=interactivity, compiler=compiler, result=result)\n"
     ]
    }
   ],
   "source": [
    "dfDefaultClassifiers = pd.read_csv(FILE_CLASSIFIERS_DEFAULT, delimiter=\";\")\n",
    "dfDefaultPreprocessors = pd.read_csv(FILE_PREPROCESSORS_DEFAULT, delimiter=\";\")\n",
    "dfDefaultPreprocessors[\"algorithmoptions\"] = \"\"\n",
    "dfConfiguredClassifiers = pd.read_csv(FILE_CLASSIFIERS_PARAMETRIZED, delimiter=\";\")\n",
    "dfConfiguredPreprocessors = pd.read_csv(FILE_PREPROCESSORS_PARAMETRIZED, delimiter=\";\")\n",
    "evaluationGridPoints = getEvaluationGridPoints()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create a Single Runtime CSV for Atomic Algorithms"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "def resolveExceptions(df):\n",
    "    \n",
    "    # Set traintime to full traintime +1 (3601) if the exception is a timeout or is dominated by another one that timed out\n",
    "    print(\"Len of df is \" + str(len(df)))\n",
    "    timeoutsTrain = {}\n",
    "    timeoutsTest = {}\n",
    "    numTimeoutsTrain = 0\n",
    "    numTimeoutsTest = 0\n",
    "    failedRuns = df[df[\"exception\"].notnull()]\n",
    "    failedRunsWithTimeout = failedRuns[failedRuns[\"exception\"].str.contains(\"AlgorithmTimeouted\") | failedRuns[\"exception\"].str.contains(\"OutOfMemory\")]\n",
    "    pbar = tqdm(total=len(failedRunsWithTimeout))\n",
    "    df[\"error\"] = [None for i in range(len(df))]\n",
    "    for i, row in failedRunsWithTimeout.iterrows():\n",
    "        pbar.update(1)\n",
    "        exception = str(row[\"exception\"])\n",
    "        if exception != df.at[i, \"exception\"]:\n",
    "            raise Exception(\"The access via at does not seem to work correctly at index \" + str(i) + \"! Expected \" + str(exception) + \" and found \" + str(df.at[i, \"exception\"])  + \"\\n\\n\" + str(row) + \"\\n\\n\" + str(df.loc[i]) + \"\\n\\nSize of df: \" + str(len(df)))\n",
    "        \n",
    "        # add the timeout to the respective list, depending on whether it occured in the train or prediction phase\n",
    "        if \"timeout\" in exception.lower():# or \"memory\" in exception.lower():\n",
    "            df.at[i, \"exception\"] = np.nan\n",
    "            df.at[i, \"error\"] = \"timeout\" if \"timeout\" in exception.lower() else \"memory\"\n",
    "            isTimeoutDuringTraining = np.isnan(row[\"fittime\"]) or row[\"fittime\"] >= 3600*10**3\n",
    "            if isTimeoutDuringTraining:\n",
    "                df.at[i, \"fittime\"] = 3600*10**3\n",
    "                openmlid = row[\"openmlid\"]\n",
    "                algo = row[\"algorithm\"]\n",
    "                if not openmlid in timeoutsTrain:\n",
    "                    timeoutsTrain[openmlid] = {}\n",
    "                if not algo in timeoutsTrain[openmlid]:\n",
    "                    timeoutsTrain[openmlid][algo] = []\n",
    "                timeoutsTrain[openmlid][algo].append((row[\"openmlid\"], row[\"algorithm\"], row[\"algorithmoptions\"], row[\"fitsize\"], row[\"fitattributes\"], i))\n",
    "                numTimeoutsTrain += 1\n",
    "            else:\n",
    "                if not np.isnan(row[\"applicationtimeperkinstances\"]):\n",
    "                    raise Exception(\"There is a timeout for row \" + str(row) + \" but fittime < 3600 and there is an application time. This should not happen!\")\n",
    "                openmlid = row[\"openmlid\"]\n",
    "                algo = row[\"algorithm\"]\n",
    "                if not openmlid in timeoutsTest:\n",
    "                    timeoutsTest[openmlid] = {}\n",
    "                if not algo in timeoutsTest[openmlid]:\n",
    "                    timeoutsTest[openmlid][algo] = []\n",
    "                timeoutsTest[openmlid][algo].append((row[\"openmlid\"], row[\"algorithm\"], row[\"algorithmoptions\"], row[\"fitsize\"], row[\"fitattributes\"], i))\n",
    "                df.at[i, \"applicationtimeperkinstances\"] = 3600*10**3 # suppose that the test time for the given data is high (apprx by 1h)\n",
    "                numTimeoutsTest += 1\n",
    "    pbar.close()\n",
    "    print(\"Found \" + str(numTimeoutsTrain) + \" timeouts during training and \" + str(numTimeoutsTest) + \" timeouts during prediction. Len of df is \" + str(len(df)))\n",
    "    \n",
    "    # now iterate over all still failed rows\n",
    "    failedRuns = df[df[\"exception\"].notna()]\n",
    "    pbar = tqdm(total=len(failedRuns))\n",
    "    for i, row in failedRuns.iterrows():\n",
    "        exception = str(row[\"exception\"])\n",
    "        if exception != df.at[i, \"exception\"]:\n",
    "            raise Exception(\"The access via at does not seem to work correctly at index \" + str(i) + \"! Expected \" + str(exception) + \" and found \" + str(df.at[i, \"exception\"]) + \"\\n\\n\" + str(row) + \"\\n\\n\" + str(df.loc[i]) + \"\\n\\nSize of df: \" + str(len(df)))\n",
    "        pbar.update(1)\n",
    "\n",
    "        # if this is not a ExperimentFailurePredictionException, continue\n",
    "        if not \"ExperimentFailurePredictionException\" in exception:\n",
    "            continue\n",
    "\n",
    "        # check whether we have a timeout prediction exception. Then we can interpolate the values\n",
    "        if \"which failed due to\" in exception:# or \"memory\" in exception:\n",
    "            openmlid = row[\"openmlid\"]\n",
    "            algo = row[\"algorithm\"]\n",
    "            options = row[\"algorithmoptions\"]\n",
    "            t = (openmlid, algo, options, int(row[\"fitsize\"]), int(row[\"fitattributes\"]), i)\n",
    "\n",
    "            resolved = False\n",
    "\n",
    "            # check on dominance by train time\n",
    "            if openmlid in timeoutsTrain and algo in timeoutsTrain[openmlid]:\n",
    "                for t2 in timeoutsTrain[openmlid][algo]:\n",
    "                    # if the datapoint is dominated by another one due to a timeout, set the traintime to that time\n",
    "                    #if openmlid == 3:\n",
    "                    #    print(t2[3], t[3], t2[3] <= t[3])\n",
    "                    #    print(t2[4], t[4], t2[4] <= t[4])\n",
    "                    #    print(options, t2[2], str(options) == str(t2[2]))\n",
    "                    if t2[3] <= t[3] and t2[4] <= t[4] and str(t2[2]) == str(options):\n",
    "                        df.at[i, \"fittime\"] = 3601*10**3\n",
    "                        df.at[i, \"exception\"] = np.nan\n",
    "                        df.at[i, \"error\"] = \"timeout\" if \"which failed due to\" in exception else \"memory\"\n",
    "                        resolved = True\n",
    "                        timeoutsTrain[openmlid][algo].append(t)\n",
    "                        break\n",
    "\n",
    "            # check on dominance by prediction time\n",
    "            if not resolved and openmlid in timeoutsTest and algo in timeoutsTest[openmlid]:\n",
    "                for t2 in timeoutsTest[openmlid][algo]:\n",
    "                    # if the datapoint is dominated by another one due to a timeout, set the traintime to that time\n",
    "                    if t2[3] <= t[3] and t2[4] <= t[4] and str(t2[2]) == str(options):\n",
    "                        dominantedIndex = t2[5]\n",
    "                        #print(dominantedIndex, df.loc[dominantedIndex])\n",
    "                        #print(\"Replacing fittime \" + str(row[\"fittime\"]) + \" by \" + str(df.at[dominantedIndex, \"fittime\"]))\n",
    "                        df.at[i, \"fittime\"] = df.at[dominantedIndex, \"fittime\"]\n",
    "                        df.at[i, \"applicationtimeperkinstances\"] = 3601*10**3\n",
    "                        df.at[i, \"exception\"] = np.nan\n",
    "                        df.at[i, \"error\"] = \"timeout\" if \"which failed due to\" in exception else \"memory\"\n",
    "                        resolved = True\n",
    "                        timeoutsTest[openmlid][algo].append(t)\n",
    "                        break\n",
    "\n",
    "            # now make sure that the exception got resolved\n",
    "            if not resolved:\n",
    "                print(\"WARNING: Could not resolve the prediction exception for algorithm \" + algo + \" on openmlid \" + str(openmlid) + \" and algorithm \" + str(algo) + \" with options '\" + str(options) + \"' for \" + str(row[\"fitsize\"]) + \" instances and \" + str(row[\"fitattributes\"]) + \" attributes. Here is the exception: \" + str(exception))\n",
    "#                raise Exception(\"Could not resolve the prediction exception for algorithm \" + algo + \" on openmlid \" + str(openmlid) + \" and algorithm \" + str(algo) + \" with options '\" + str(options) + \"' for \" + str(row[\"fitsize\"]) + \" instances and \" + str(row[\"fitattributes\"]) + \" attributes. Here is the exception: \" + str(exception))\n",
    "\n",
    "    pbar.close()\n",
    "    \n",
    "    print(\"Setting runtime of lines with remaining exceptions (domain-specific) to -1.\")\n",
    "    replaced = 0\n",
    "    for i, row in tqdm(df[df[\"exception\"].notna()].iterrows()):\n",
    "        df.at[i, \"fittime\"] = -1\n",
    "        df.at[i, \"applicationtimeperkinstances\"] = np.nan\n",
    "        exception = df.at[i, \"exception\"].lower()\n",
    "        if \"smote\" in exception:\n",
    "            df.at[i, \"exception\"] = np.nan\n",
    "            df.at[i, \"error\"] = \"smote\"\n",
    "        elif \"memory\" in exception:\n",
    "            df.at[i, \"exception\"] = np.nan\n",
    "            df.at[i, \"error\"] = \"memory\"\n",
    "        else:\n",
    "            df.at[i, \"exception\"] = np.nan\n",
    "            df.at[i, \"error\"] = \"other\"\n",
    "        replaced += 1\n",
    "    df = df.drop(columns=[\"exception\"])\n",
    "    \n",
    "    print(\"There are now \" + str(np.count_nonzero(df[\"fittime\"].isna())) + \" lines where fittime is not available.\")\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data frame for atomic algorithms ready.\n"
     ]
    }
   ],
   "source": [
    "relevantTrainMetafeatures = ['fitsize', 'fitattributes', 'numattributes', 'numlabels', 'numnumericattributes', 'numsymbolicattributes', 'numberofcategories', 'numericattributesafterbinarization', 'totalvariance', 'attributestocover50pctvariance', 'attributestocover90pctvariance', 'attributestocover95pctvariance', 'attributestocover99pctvariance']\n",
    "\n",
    "# prepare classifier data frame\n",
    "dfAlgorithms = pd.concat([dfDefaultClassifiers, dfConfiguredClassifiers, dfDefaultPreprocessors, dfConfiguredPreprocessors], ignore_index = True, sort=False)\n",
    "allAttributes = ['openmlid', 'totalsize', 'algorithm', 'algorithmoptions', 'seed']\n",
    "allAttributes.extend([\"f1_\" + x for x in relevantTrainMetafeatures])\n",
    "allAttributes.extend(['applicationsize', 'fittime', 'applicationtimeperkinstances', 'exception'])\n",
    "renameDict = {}\n",
    "for a in relevantTrainMetafeatures:\n",
    "    if a != \"numattributes\":\n",
    "        renameDict[\"f1_\" + a] =  a\n",
    "dfClassifiersMod = dfAlgorithms.rename(columns=renameDict)\n",
    "dfClassifiersMod = dfClassifiersMod[[x.replace(\"f1_\", \"\") for x in allAttributes]]\n",
    "dfAtomic = dfClassifiersMod.copy()\n",
    "print (\"Data frame for atomic algorithms ready.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Resolve Exceptions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Len of df is 1825559\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "fd778a86a25542d48bde42d634e5deae",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(FloatProgress(value=0.0, max=92597.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Found 67238 timeouts during training and 5835 timeouts during prediction. Len of df is 1825559\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bfdbef28f4ec473e917809e9b64e01de",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(FloatProgress(value=0.0, max=234490.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 30000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 47893, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 40000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 47893, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 743 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46972, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 772 and algorithm logistic with options 'nan' for 6000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46412, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 772 and algorithm logistic with options 'nan' for 6000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46412, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 904 and algorithm logistic with options 'nan' for 6000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46415, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 4000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46049, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 4000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 914 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 46977, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 4000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 4000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 772 and algorithm logistic with options 'nan' for 6000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 11584, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 904 and algorithm logistic with options 'nan' for 6000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16003, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 6000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 772 and algorithm logistic with options 'nan' for 6000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 11584, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 6000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 904 and algorithm logistic with options 'nan' for 8000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16003, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 743 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 11211, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 904 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16003, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 914 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 17066, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 10000 instances and 18000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 743 and algorithm logistic with options 'nan' for 10000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 11211, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 923 and algorithm logistic with options 'nan' for 10000 instances and 20000 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 16875, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 30000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 40000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 50000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 60000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 70000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 80000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 90000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:109)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n",
      "WARNING: Could not resolve the prediction exception for algorithm logistic on openmlid 57 and algorithm logistic with options 'nan' for 100000 instances and 100 attributes. Here is the exception: \n",
      "\tError class: ai.libs.jaicore.experiments.exceptions.ExperimentFailurePredictionException\n",
      "\tError message: Experiment will fail for the following reason: This has at least as much instances and attributes as 2990, which failed due to a timeout.\n",
      "\tError trace:\n",
      "\t\ttpami.basealgorithmlearning.datagathering.ALearnerExperimentEvaluator.checkFail(ALearnerExperimentEvaluator.java:110)\n",
      "\t\ttpami.basealgorithmlearning.datagathering.AMLAlgorithmExperimentEvaluator.evaluate(AMLAlgorithmExperimentEvaluator.java:118)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.conductExperiment(ExperimentRunner.java:217)\n",
      "\t\tai.libs.jaicore.experiments.ExperimentRunner.lambda$randomlyConductExperiments$0(ExperimentRunner.java:104)\n",
      "\t\tjava.base/java.lang.Thread.run(Thread.java:834)\n"
     ]
    }
   ],
   "source": [
    "dfAtomic = resolveExceptions(dfAtomic)\n",
    "print(\"Now removing lines where fitattributes is not available.\")\n",
    "dfAtomic = dfAtomic[(dfAtomic[\"fitattributes\"].notnull()) & (dfAtomic[\"fittime\"].notnull())]\n",
    "print(\"Ready. Prepared clean dataset.\")\n",
    "dfAtomic = dfAtomic.astype({\"fitattributes\": int, \"fittime\": int})"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Write Runtime File"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dfAtomic.to_csv(\"data/runtimes/runtimes_atomic.csv\", index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Files Relevant for Using the Approach in ML-Plan\n",
    "What follows after this is not relevant for the python-based analysis and can be skipped for the first phase."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Compile One CSV-File per Atomic Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (3,21) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  interactivity=interactivity, compiler=compiler, result=result)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv(\"data/runtimes/runtimes_atomic.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "def explodeToFiles(df, binarize):\n",
    "    algorithms = pd.unique(df[\"algorithm\"])\n",
    "    df = df[df[\"fittime\"] > 0].copy()\n",
    "    df[\"msize\"] = df[\"fitsize\"] * df[\"fitattributes\"]\n",
    "    df[\"msize2\"] = df[\"fitsize\"] * (df[\"fitattributes\"] ** 2)\n",
    "    for a in tqdm(algorithms):\n",
    "        print(a)\n",
    "        columns = [\"openmlid\", \"fitsize\", \"fitattributes\", \"msize\", \"msize2\"]\n",
    "        dfAlg = df[df[\"algorithm\"] == a]\n",
    "        dfAlgDefaults = dfAlg[dfAlg[\"algorithmoptions\"].isnull()]\n",
    "        dfAlgParametrized = dfAlg[dfAlg[\"algorithmoptions\"].notnull()]\n",
    "        \n",
    "        # create a file for the parametrized version (if applicable)\n",
    "        if len(dfAlgParametrized) > 0:\n",
    "            lenBefore = len(dfAlgParametrized)\n",
    "            dfTarget = dfAlgParametrized.merge(dfAlgDefaults, on=[\"openmlid\", \"algorithm\", \"seed\", \"fitsize\", \"fitattributes\"], suffixes=(\"\", \"_def\"))\n",
    "            if lenBefore != len(dfTarget):\n",
    "                warning(\"Size has changed from \" + str(lenBefore) + \" to \" + str(len(dfTarget)) + \"! This may come due to errored executions etc. but should be checked.\")\n",
    "            columnsbeforeExplosion = list(dfTarget.columns)\n",
    "            if len(dfTarget) > 0:\n",
    "                dfTarget = explodeAlgorithmOptions(dfTarget, binarize=binarize)\n",
    "                algoParams = [x for x in dfTarget.columns if not x in columnsbeforeExplosion]\n",
    "                for x in [\"searcheroptions\", \"evaloptions\"]:\n",
    "                    if x in algoParams:\n",
    "                        algoParams.remove(x)\n",
    "                columns.extend(algoParams)\n",
    "                columns.extend([\"fittime_def\", \"applicationtimeperkinstances_def\", \"fittime\", \"applicationtimeperkinstances\"])\n",
    "                dfTarget[columns].fillna(-1).astype({\"fitattributes\": int, \"applicationtimeperkinstances\": int, \"applicationtimeperkinstances_def\": int}).to_csv(\"data/runtimes/atomic/runtimes_\" + a + \"_parametrized.csv\", index=False)\n",
    "            else:\n",
    "                print(\"No file written, no entries for algorithm \" + a)\n",
    "            \n",
    "        # create a file for the default version\n",
    "        dfTarget = dfAlgDefaults.rename(columns={\"fittime\": \"fittime_def\", \"applicationtimeperkinstances\": \"applicationtimeperkinstances_def\"})\n",
    "        dfTarget[[\"openmlid\", \"fitsize\", \"fitattributes\", \"msize\", \"msize2\", \"fittime_def\", \"applicationtimeperkinstances_def\"]].fillna(-1).astype({\"fitattributes\": int, \"applicationtimeperkinstances_def\": int}).to_csv(\"data/runtimes/atomic/runtimes_\" + a + \"_default.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "explodeToFiles(df, False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
